### ISSUE TITLE
Label Markers Disappearing

### ISSUE THREAD

**Issue by Sanunez** [heremaps/here-android-sdk-examples#249] opened 2019-05-29 00:33 UTC
Is there a way to force multiple markers to show on map? My use case requires all points to be visible at once, but the markers keep disappearing despite overlapping being enabled.

(Note: I have hundreds of markers that need to be shown together)

**Comment by starand** [comment] 2019-05-29 06:18
@Sanunez,
Do you use Premium SDK? Which version?
Could you please share snippet of code how you use markers?

**Comment by Sanunez** [comment] 2019-05-29 15:52
I am using the premium SDK v3.11.2.82.
Below is the java code where I create a MapLabeledMarker and add it to the map.
``` java
for(Client client: clientList){
  String icon = client.getRecompensa() ? "recIcon" : "default";
  Image markerIcon = new Image();
  if(client.getRecompensa()){
    markerIcon.setBitmap(getIcon(FontAwesome.Icon.faw_store, R.color.markerRed));
  }else{
    markerIcon.setBitmap(getIcon(FontAwesome.Icon.faw_dollar_sign, R.color.markerGreen));
  }
  MapLabeledMarker mm = new MapLabeledMarker(new GeoCoordinate(client.getLatitude(), client.getLongitude()), markerIcon);
  mm.setFontScalingFactor(2.0f);
  mm.setFadingAnimationEnabled(false);
  mm.setTransparency(1);
  mm.setDeclutteringEnabled(false);
  mm.setLabelText("ENG", client.getName());
  mm.setOverlappingEnabled(true);
  mm.setVisible(true);
  map.addMapObject(mm);
}
```

**Comment by Merlin1stHere** [comment] 2019-05-30 12:39
@Sanunez
This is the default behavior. MabLabeledMarkers are processed together with other labels on the map (street names and etc.), but they have lower priority.
Try to add these lines to your code:
**mm.setOverlayType(MapOverlayType.FOREGROUND_OVERLAY);**
**mm.setReserveOverlayType(MapOverlayType.BACKGROUND_OVERLAY);**

**Comment by starand** [comment] 2019-06-07 10:56
@Sanunez, if there is no further questions we will close the issue.

**Comment by Sanunez** [comment] 2019-06-07 20:35
I have applied the above code and although it made the behavior a bit better, it is still not quite working.

Markers are still being hidden and displayed sporadically, as well as Labels being hidden and shown depending on zoom level

**Comment by starand** [comment] 2019-06-26 05:37
@Sanunez, the fix is planned in scope of SDK 3.13.

**Comment by starand** [comment] 2019-11-13 15:08
@Sanunez Did you double check whether the issue is gone with SDK 3.13?

**Closed** 2020-01-10 13:47 UTC

**Comment by Sanunez** [comment] 2020-01-10 17:37
@starand, To be honest I stopped using the SDK for this reason.
