### ISSUE TITLE
Cannot created HERE SDK objects before MapEngine is initialized.

### ISSUE THREAD

**Issue by paramtrivedi** [heremaps/here-android-sdk-examples#19] opened 2017-04-11 19:31 UTC
I am accessing the sample application and getting the error. Can any one please help here?

FATAL EXCEPTION: main
                                                                                   Process: com.here.android.example.guidance, PID: 30111
                                                                                   com.here.android.mpa.common.UnintializedMapEngineException: Cannot created HERE SDK objects before MapEngine is initialized.  See MapEngine.init()

**Comment by paramtrivedi** [comment] 2017-04-11 19:42
I am getting a toast OPERATION_NOT_ALLOWED.

**Comment by sschuberth** [comment] 2017-04-11 19:51
Hi @paramtrivedi, are you sure you've generated / used the correct app id / app code for the package name of the example you're trying?

**Comment by paramtrivedi** [comment] 2017-04-12 22:59
Changing the keys solved the issue. Thank you.

**Comment by paramtrivedi** [comment] 2017-06-14 19:27
@sschuberth 

@sschuberth Hi Sebestien, 

I have a problem with the here maps sdk when there are more waypoints in the turn. 

It is crashing from the NavigationManager with this error which stops us to debug as it is from the here maps sdk error - 

A/libc: **Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 3325 (NavigationManager)**

**Comment by JH-YVR** [comment] 2017-06-14 19:45
@paramtrivedi , since this is a different issue to the one originally raised and addressed, please create a separate thread for this new issue. Please create it on https://stackoverflow.com/questions/tagged/here-api as this site is intended only for topics related to the SDK examples and not general SDK topics.

**Comment by sschuberth** [comment] 2017-06-14 20:17
In addition to what @JH-YVR said, the SIGSEGV sounds like a duplicate of https://github.com/heremaps/here-android-sdk-examples/issues/48, so I'm again closing this.

**Closed by sschuberth** 2017-06-14 20:17 UTC
