### ISSUE TITLE
HereMaps in DialogFragment Any idea how to refresh or reload maps

### ISSUE THREAD

**Issue by aliexalter** [heremaps/here-android-sdk-examples#47] opened 2017-06-02 21:55 UTC
Hi Can you please put example of having Map in DialogFragment. 
Specially I have the listView with different latitude and longitude, When I an item it opens DialogFragment which shows the map with route to the clicked item lat,lng. 
**Problem is on first click maps are loaded successfully I can see all tiles and routing line. But When I click second item or any same item again it shows map without tiles.** 
Here is my code

import android.app.DialogFragment;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.here.android.mpa.common.GeoCoordinate;
import com.here.android.mpa.common.OnEngineInitListener;
import com.here.android.mpa.mapping.Map;
import com.here.android.mpa.mapping.MapFragment;
import com.here.android.mpa.mapping.MapRoute;
import com.here.android.mpa.routing.RouteManager;
import com.here.android.mpa.routing.RouteOptions;
import com.here.android.mpa.routing.RoutePlan;
import com.here.android.mpa.routing.RouteResult;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.List;

public class MapViewDialogFragment extends DialogFragment {

    private JSONObject jsonJob;

    // map embedded in the map fragment
    private Map map = null;
    private MapRoute m_mapRoute;
    final String MAP_TAG = "map_tag";

    // map fragment embedded in this activity
    private MapFragment mapFragment = null;

    private boolean paused = false;

    private View rootView;

    private Double clat;
    private Double clng;
    private Double dlat;
    private Double dlng;

    public MapViewDialogFragment() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        rootView = inflater.inflate(R.layout.fragment_map_view_dialog, container, false);

        String jobContent = this.getArguments().getString("JOB_KEY");
        try {
            jsonJob = new JSONObject(jobContent);
            String collection = jsonJob.getString("CollectionJson");
            String delivery = jsonJob.getString("DeliveryJson");
            JSONObject colJson = new JSONObject(collection);
            JSONObject delJson = new JSONObject(delivery);
            clat = colJson.getDouble("latitude");
            clng = colJson.getDouble("longitude");
            dlat = delJson.getDouble("latitude");
            dlng = delJson.getDouble("longitude");

            Log.e("LaLng---OOO",String.format("%f,%f -- %f,%f",clat,clng,dlat,dlng));

            // Search for the map fragment to finish setup by calling init().
            mapFragment = (MapFragment) getFragmentManager().findFragmentById(R.id.mapRouteFragment);
            mapFragment.init(this.getContext(), new OnEngineInitListener() {
                @Override
                public void onEngineInitializationCompleted(
                        OnEngineInitListener.Error error)
                {
                    if (error == OnEngineInitListener.Error.NONE) {
                        // retrieve a reference of the map from the map fragment
                        map = mapFragment.getMap();
                        // Set the map center to the Vancouver region (no animation)
                        map.setCenter(new GeoCoordinate(clng, clat, 0.0),
                                Map.Animation.NONE);
                        // Set the zoom level to the average between min and max
                        map.setZoomLevel(7);

                        // Declare the rm variable (the RouteManager)
                        RouteManager rm = new RouteManager();
                        // Create the RoutePlan and add two waypoints
                        RoutePlan routePlan = new RoutePlan();
                        routePlan.addWaypoint(new GeoCoordinate(clng, clat));
                        routePlan.addWaypoint(new GeoCoordinate(dlng, dlat));
                        // Create the RouteOptions and set its transport mode & routing type
                        RouteOptions routeOptions = new RouteOptions();
                        routeOptions.setTransportMode(RouteOptions.TransportMode.CAR);
                        routeOptions.setRouteType(RouteOptions.Type.FASTEST);

                        routePlan.setRouteOptions(routeOptions);

                        // Calculate the route
                        rm.calculateRoute(routePlan, new RouteListener());

                    } else {
                        Log.e("HereMaps","ERROR: Cannot initialize Map Route Fragment "+error.toString());
                    }
                }
            });
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return rootView;
    }

    private class RouteListener implements RouteManager.Listener {

        // Method defined in Listener
        public void onProgress(int percentage) {
            // Display a message indicating calculation progress
        }

        // Method defined in Listener
        public void onCalculateRouteFinished(RouteManager.Error error, List<RouteResult> routeResult) {
            // If the route was calculated successfully
            if (error == RouteManager.Error.NONE) {
                // Render the route on the map
                m_mapRoute = new MapRoute(routeResult.get(0).getRoute());
                map.addMapObject(m_mapRoute);
            }
            else {
                // Display a message indicating route calculation failure
            }
        }
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (map != null && m_mapRoute != null) {
            map.removeMapObject(m_mapRoute);
            m_mapRoute = null;
            //map = null;
        }
        if (mapFragment != null)
            getFragmentManager().beginTransaction().remove(mapFragment).commit();
    }

    @Override
    public void onResume() {

        // TODO Auto-generated method stub
        super.onResume();
        map = mapFragment.getMap();
    }
}
`

**Comment by aliexalter** [comment] 2017-06-02 21:57
I think MapEngine is already initialise I have to make re-init and for that I have to make MapEngine null onDestroyView()

**Comment by aliexalter** [comment] 2017-06-05 10:14
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/mapFragmentContainer"
    tools:context="com.***.***.MapViewDialogFragment">

    <!-- Map Fragment embedded with the map object-->
    <fragment
        android:id="@+id/mapRouteFragment"
        class="com.here.android.mpa.mapping.MapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>
```

**Comment by aliexalter** [comment] 2017-06-21 13:00
any update??

**Comment by sschuberth** [comment] 2017-06-21 13:32
Hi @aliexalter. If you're a paid customer you should have access to a dedicated support channel. Please use that channel to get more timely support on Premium SDK issues. Thanks!

**Comment by pateljc** [comment] 2017-09-11 11:36
@aliexalter have you got any solution..?? 
i m suffering with the same issue.
thank u.

**Comment by aliexalter** [comment] 2017-09-11 11:54
@pateljc Not yet.

**Comment by JohnLXiang** [comment] 2017-09-11 18:29
Hi @aliexalter , from the code snippet you provided, I didn't spot any issue. Did your code give you any error logs when initializing the MapFragment each time?

I also experimentally tried something on my side. Basically I just tried to show a DialogFragment with map when I clicked each list view item. It worked fine with following code.


`public class MapViewDialogFragment extends DialogFragment {

    private View rootView;
    private MapFragment mapFragment;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.dialog_mapfragment_test, container, false);
        mapFragment = (MapFragment) getFragmentManager().findFragmentById(R.id.mapRouteFragment);
        mapFragment.init(this.getActivity(), new OnEngineInitListener() {
            @Override public void onEngineInitializationCompleted(Error error) {
                
            }
        });

        return rootView;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (mapFragment != null)
            getFragmentManager().beginTransaction().remove(mapFragment).commit();
    }

}
`

Then I called
` DialogFragment newFragment = new MapViewDialogFragment();
        newFragment.show(getFragmentManager(), "dialog");`  in the ListView to show this dialog fragment. The map did rendered every time.

Could your try this on your machine?

**Comment by aliexalter** [comment] 2017-09-12 07:24
@JohnLXiang I am getting this error now.
E/HereMaps: ERROR: Cannot initialize Map Route Fragment FILE_RW_ERROR

**Comment by aliexalter** [comment] 2017-09-12 07:33
@JohnLXiang thanks it worked now.  I updated the SDK.

**Comment by aliexalter** [comment] 2017-09-12 07:34
Make sure permissions are given to write to file in app manifest and in main activity.

**Comment by sschuberth** [comment] 2017-09-12 07:36
Thanks @JohnLXiang for the help. @aliexalter, if the issue is resolved for you, please remember to close it. Thanks again all!

**Closed** 2017-09-12 07:38 UTC
